[package]
name = "millegrilles_maitredescles"
version = "2026.4.14"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# millegrilles_common_rust = { git = "https://github.com/dugrema/millegrilles_common_rust.git", tag = "2026.3-release" }
millegrilles_common_rust = { git = "https://github.com/dugrema/millegrilles_common_rust.git", branch = "master" }
# millegrilles_common_rust = { path = "/home/mathieu/RustroverProjects/millegrilles_common_rust" }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
serde = { version = "1.0.228", features = ["derive"] }
# sqlite = { version = "0.37.0" }
zeroize = "1.8.2"
